"""
Defines the other various layers and modules needed for building adn training the SignalingModel.
"""

from annotated_types import Ge
from typing import Dict, Union, Annotated

import numpy as np 

import torch
import torch.nn as nn

class ProjectInput(nn.Module):
    """Generate all nodes for the signaling network and linearly scale input ligand values by NN parameters."""
    def __init__(self, node_idx_map: Dict[str, int], input_labels: np.array, projection_amplitude: Union[int, float] = 1, dtype: torch.dtype=torch.float32, device: str = 'cpu'):
        """Initialization method.

        Parameters
        ----------
        node_idx_map : Dict[str, int]
            a dictionary mapping node labels (str) to the node index (float)
            generated by `SignalingModel.parse_network`
        input_labels : np.array
            names of the input nodes (ligands) from net
        projection_amplitude : Union[int, float]
            value with which to initialize learned linear scaling parameters, by default 1. (if turn require_grad = False for this layer, this is still applied simply as a constant linear scalar in each forward pass)
        dtype : torch.dtype, optional
            datatype to store values in torch, by default torch.float32
        device : str
            whether to use gpu ("cuda") or cpu ("cpu"), by default "cpu"
        """
        super().__init__()

        self.device = device
        self.dtype = dtype
        self.projection_amplitude = projection_amplitude
        self.size_out = len(node_idx_map) # number of nodes total in prior knowledge network
        self.input_node_idx = torch.tensor([node_idx_map[x] for x in input_labels], device = self.device) # idx representation of ligand inputs
        weights = self.projection_amplitude * torch.ones(len(input_labels), dtype=self.dtype, device = self.device) # scaled input weights
        self.weights = nn.Parameter(weights)
        
    def forward(self, X_in: torch.Tensor):
        """Learn the weights for the input ligands to the signaling network (if grad_fn set to False, 
        simply scales by projection amplitude).
        Transform from ligand input (samples x ligands) to full signaling network (samples x network nodes).

        Parameters
        ----------
        X_in : torch.Tensor
            the ligand concentration inputs. Shape is (samples x ligands). 

        Returns
        -------
        X_full :  torch.Tensor
            the linearly scaled ligand inputs. Shape is (samples x network nodes)
        """
        X_full = torch.zeros([X_in.shape[0],  self.size_out], dtype=self.dtype, device=self.device) # shape of (samples x total nodes in network)
        X_full[:, self.input_node_idx] = self.weights * X_in # only modify those nodes that are part of the input (ligands)
        return X_full
    
    def L2_reg(self, lambda_L2: Annotated[float, Ge(0)] = 0):
        """Get the L2 regularization term for the neural network parameters.
        Here, this pushes learned parameters towards `projection_amplitude` 
        
        Parameters
        ----------
        lambda_2 : Annotated[float, Ge(0)]
            the regularization parameter, by default 0 (no penalty) 
        
        Returns
        -------
        projection_L2 : torch.Tensor
            the regularization term
        """
        # if removed the `- self.projection_amplitude` part, would force weights to 0, thus shrinking ligand inputs
        projection_L2 = lambda_L2 * torch.sum(torch.square(self.weights - self.projection_amplitude))  
        return projection_L2

class ProjectOutput(nn.Module):
    """Transforms signaling network to TF activity."""
    def __init__(self, node_idx_map: Dict[str, int], output_labels: np.array,
                    projection_amplitude: Union[int, float] = 1,
                    dtype: torch.dtype=torch.float32, device: str = 'cpu'):
        """Initialization method.
    
        Parameters
        ----------
        node_idx_map : Dict[str, int]
            a dictionary mapping node labels (str) to the node index (float)
            generated by `SignalingModel.parse_network`
        output_labels : np.array
           names of the out nodes (TFs) from net
        projection_amplitude : Union[int, float], optional
            value with which to initialize learned linear scaling parameters, by default 1. 
            (if turn require_grad = False for this layer, this is still applied  simply 
            as a constant linear scalar in each forward pass)
        dtype : torch.dtype, optional
            datatype to store values in torch, by default torch.float32
        device : str, optional
            whether to use gpu ("cuda") or cpu ("cpu"), by default "cpu"
        """
        super().__init__()

        self.size_in = len(node_idx_map)
        self.size_out = len(output_labels)
        self.projection_amplitude = projection_amplitude

        self.output_node_order = torch.tensor([node_idx_map[x] for x in output_labels], device = device) # idx representation of TF outputs

        weights = self.projection_amplitude * torch.ones(self.size_out, dtype=dtype, device = device)
        self.weights = nn.Parameter(weights)

    def forward(self, Y_full):
        """Learn the weights for the output TFs of the signaling network (if grad_fn set to False, 
        simply scales by projection amplitude).
        Transforms full signaling network  (samples x network nodes) to only the space of the TFs.

        Parameters
        ----------
        Y_full : torch.Tensor
            the signaling network scaled by learned interaction weights. Shape is (samples x network nodes). 
            Output of BioNet.

        Returns
        -------
        Y_hat :  torch.Tensor
            the linearly scaled TF outputs. Shape is (samples x TFs)
        """
        Y_hat = self.weights * Y_full[:, self.output_node_order]
        return Y_hat

    def L2_reg(self, lambda_L2: Annotated[float, Ge(0)] = 0):
        """Get the L2 regularization term for the neural network weight parameters.
        Here, this pushes learned parameters towards `projection_amplitude` 
        
        Parameters
        ----------
        lambda_2 : Annotated[float, Ge(0)]
            the regularization parameter, by default 0 (no penalty) 
        
        Returns
        -------
        projection_L2 : torch.Tensor
            the regularization term
        """
        projection_L2 = lambda_L2 * torch.sum(torch.square(self.weights - self.projection_amplitude))  
        return projection_L2
    
    # def set_device(self, device: str):
    #     """Sets torch.tensor objects to the device
        
    #     Parameters
    #     ----------
    #     device : str
    #         set to use gpu ("cuda") or cpu ("cpu")
    #     """
    #     self.output_node_order = self.output_node_order.to(device)

