"""
Defines the other various layers and modules needed for building and training the SignalingModel.
"""

from annotated_types import Ge
from collections import OrderedDict
from typing import Dict, Union, Annotated, List
import warnings

import numpy as np 

import torch
import torch.nn as nn
import torch.nn.functional as F

from ..utilities import set_seeds
from .model_utilities import L2_reg
from .activation_functions import activation_function_torch_map

class ProjectInput(nn.Module):
    """Generate all nodes for the signaling network and linearly scale input ligand values by NN parameters."""
    def __init__(self, node_idx_map: Dict[str, int], input_labels: np.array, projection_amplitude: Union[int, float] = 1, dtype: torch.dtype=torch.float32, device: str = 'cpu'):
        """Initialization method.

        Parameters
        ----------
        node_idx_map : Dict[str, int]
            a dictionary mapping node labels (str) to the node index (float)
            generated by `SignalingModel.parse_network`
        input_labels : np.array
            names of the input nodes (ligands) from net
        projection_amplitude : Union[int, float]
            value with which to initialize learned linear scaling parameters, by default 1. (if turn require_grad = False for this layer, this is still applied simply as a constant linear scalar in each forward pass)
        dtype : torch.dtype, optional
            datatype to store values in torch, by default torch.float32
        device : str
            whether to use gpu ("cuda") or cpu ("cpu"), by default "cpu"
        """
        super().__init__()

        self.device = device
        self.dtype = dtype
        self.projection_amplitude = projection_amplitude
        self.size_out = len(node_idx_map) # number of nodes total in prior knowledge network
        self.input_node_idx = torch.tensor([node_idx_map[x] for x in input_labels], device = self.device) # idx representation of ligand inputs
        weights = self.projection_amplitude * torch.ones(len(input_labels), dtype=self.dtype, device = self.device) # scaled input weights
        self.weights = nn.Parameter(weights)
        
    def forward(self, X_in: torch.Tensor):
        """Learn the weights for the input ligands to the signaling network (if grad_fn set to False, 
        simply scales by projection amplitude).
        Transform from ligand input (samples x ligands) to full signaling network (samples x network nodes).

        Parameters
        ----------
        X_in : torch.Tensor
            the ligand concentration inputs. Shape is (samples x ligands). 

        Returns
        -------
        X_full :  torch.Tensor
            the linearly scaled ligand inputs. Shape is (samples x network nodes)
        """
        X_full = torch.zeros([X_in.shape[0],  self.size_out], dtype=self.dtype, device=self.device) # shape of (samples x total nodes in network)
        X_full[:, self.input_node_idx] = self.weights * X_in # only modify those nodes that are part of the input (ligands)
        return X_full
    
    def L2_reg(self, lambda_L2: Annotated[float, Ge(0)] = 0):
        """Get the L2 regularization term for the neural network parameters.
        Here, this pushes learned parameters towards `projection_amplitude` 
        
        Parameters
        ----------
        lambda_2 : Annotated[float, Ge(0)]
            the regularization parameter, by default 0 (no penalty) 
        
        Returns
        -------
        projection_L2 : torch.Tensor
            the regularization term
        """
        # if removed the `- self.projection_amplitude` part, would force weights to 0, thus shrinking ligand inputs
        projection_L2 = L2_reg(lambda_L2, parameter = (self.weights - self.projection_amplitude ))
        return projection_L2

class ProjectOutput(nn.Module):
    """Transforms signaling network to TF activity."""
    def __init__(self, node_idx_map: Dict[str, int], output_labels: np.array,
                    projection_amplitude: Union[int, float] = 1,
                    dtype: torch.dtype=torch.float32, device: str = 'cpu'):
        """Initialization method.
    
        Parameters
        ----------
        node_idx_map : Dict[str, int]
            a dictionary mapping node labels (str) to the node index (float)
            generated by `SignalingModel.parse_network`
        output_labels : np.array
           names of the out nodes (TFs) from net
        projection_amplitude : Union[int, float], optional
            value with which to initialize learned linear scaling parameters, by default 1. 
            (if turn require_grad = False for this layer, this is still applied  simply 
            as a constant linear scalar in each forward pass)
        dtype : torch.dtype, optional
            datatype to store values in torch, by default torch.float32
        device : str, optional
            whether to use gpu ("cuda") or cpu ("cpu"), by default "cpu"
        """
        super().__init__()

        self.size_in = len(node_idx_map)
        self.size_out = len(output_labels)
        self.projection_amplitude = projection_amplitude

        self.output_node_order = torch.tensor([node_idx_map[x] for x in output_labels], device = device) # idx representation of TF outputs

        weights = self.projection_amplitude * torch.ones(self.size_out, dtype=dtype, device = device)
        self.weights = nn.Parameter(weights)
        
        bias = torch.zeros(len(output_labels)).to(device, dtype)
        self.bias = nn.Parameter(bias)

    def forward(self, Y_full):
        """Learn the weights for the output TFs of the signaling network (if grad_fn set to False, 
        simply scales by projection amplitude).
        Transforms full signaling network  (samples x network nodes) to only the space of the TFs.

        Parameters
        ----------
        Y_full : torch.Tensor
            the signaling network scaled by learned interaction weights. Shape is (samples x network nodes). 
            Output of BioNet.

        Returns
        -------
        Y_hat :  torch.Tensor
            the linearly scaled TF outputs. Shape is (samples x TFs)
        """
        Y_hat = (self.weights * Y_full[:, self.output_node_order]) + self.bias 
        return Y_hat

    def L2_reg(self, 
               weights_lambda_L2: Annotated[float, Ge(0)] = 0, 
              bias_lambda_L2: Annotated[float, Ge(0)] = 0):
        """Get the L2 regularization term for the neural network parameters.
        Here, this pushes learned parameters towards `projection_amplitude` 
        
        Parameters
        ----------
        weights_lambda_L2 : Annotated[float, Ge(0)]
            the regularization parameter for the weights, by default 0 (no penalty) 
        bias_lambda_L2 : Annotated[float, Ge(0)]
            the regularization parameter for the weights, by default 0 (no penalty) 
        
        Returns
        -------
        projection_L2 : torch.Tensor
            the regularization term
        """
        weight_loss = L2_reg(weights_lambda_L2, (self.weights - self.projection_amplitude))
        biass_loss = L2_reg(bias_lambda_L2, self.bias)
#         return weight_loss + biass_loss
        return OrderedDict({'weight_loss': weight_loss, 'bias_loss': biass_loss})
    
    # def set_device(self, device: str):
    #     """Sets torch.tensor objects to the device
        
    #     Parameters
    #     ----------
    #     device : str
    #         set to use gpu ("cuda") or cpu ("cpu")
    #     """
    #     self.output_node_order = self.output_node_order.to(device)    
    
class FCLayers(nn.Module):
    """
    Generates standard, fully-connected neural-network.
    Adapted from scVI's `FCLayers`.
    """
    DEFAULT_HYPER_PARAMS = {'batch_momentum': 0.01, 'layer_norm': False, 'spectral_norm': False,
                            'dropout_rate': 0.1,
                        'activation_fn': nn.ReLU, # can make as None to have purely linear
                            # 'initialize': True
                        }
    def __init__(self, layers: List[int],
                 batch_momentum: float = 0.01,
                 layer_norm: bool = False,
                 spectral_norm: bool = False,
                 dropout_rate: int | float = 0.1,
                 activation_fn: nn.Module | None = nn.ReLU,
                #  initialize: bool = True,
                 dtype: torch.dtype=torch.float32,
                 device: str = 'cpu', 
                ):
        """Initialize encoder.

        Parameters
        ----------
        layers : List[int]
            the size of each layer (including inputs and outputs)
            each element in the list corresponds to one hidden layer (i.e., no. of hidden layers = length of list)
        batch_momentum : float, optional
            `momentum` parameter for `BatchNorm` layer, by default .01
            If None, a `BatchNorm` is not added
        layer_norm : bool, optional
            whether to have `LayerNorm` layers or not, by default False
        spectral_norm : bool, optional
            whether to apply spectral normalization (`torch.nn.utils.spectral_norm`) to the linear layers of the model
        dropout_rate : int | float, optional
            dropout rate to apply to each of the hidden layers, by default 0.1
            If None, dropout is not added
        activation_fn : nn.Module | None, optional
            non-linear Pytorch activation function, by default nn.ReLU. No activation if set to None
        linear_output : bool, optional
            whether the final layer in the encoder should only be linear (True) or incorporate the specified `activation_fn` (False)
        initialize: bool, optional
            whether to initialize the linear layer weights using `torch.nn.init`, by default False
        device : str
            whether to use gpu ("cuda") or cpu ("cpu"), by default "cpu"
        dtype : torch.dtype, optional
            datatype to store values in torch, by default torch.float32
        """
        super().__init__()

        # set up params
        self.batch_momentum = batch_momentum
        self.layer_norm = layer_norm
        self.spectral_norm = spectral_norm
        self.dropout_rate = dropout_rate
        self.activation_fn = activation_fn
        self.dtype = dtype
        self.device = device
        # self.initialize = initialize

        # check only one type of normalization is being applied
        norm_flags = [
            self.batch_momentum is not None,
            self.layer_norm,
            self.spectral_norm
        ]

        if sum(norm_flags) > 1:
            raise ValueError('You have applied a combination of batch-, layer-, and spectral normalization. Choose only one.')

        fc_layers = OrderedDict()
        for i, (n_in, n_out) in enumerate(zip(layers[:-1], layers[1:])):
                fc_layers['FC Layer {}'.format(i)] = self._single_layer(n_in,n_out)#, drop_keys = None)
        self.fc_layers = nn.Sequential(fc_layers)

    def _single_layer(self, n_in: int, n_out: int):#, drop_keys: Optional[List[str]] = None):
        """Creates a single [set of] layer[s] in the encoder."""

        linear_layer = nn.Linear(in_features = n_in, out_features = n_out, bias = True, 
                                                       device = self.device, dtype = self.dtype)
        
        # if self.initialize:
        self._initialize_weights(linear_layer)
        if self.spectral_norm:
            linear_layer = nn.utils.spectral_norm(linear_layer)
        
        all_layers = OrderedDict([('linear', linear_layer),
                                  ('batch normalization', nn.BatchNorm1d(n_out, momentum=self.batch_momentum, 
                                                                         device = self.device, dtype = self.dtype) if self.batch_momentum else None),
                                  ('layer normalization', nn.LayerNorm(n_out, elementwise_affine=False, 
                                                                       device = self.device, dtype = self.dtype) if self.layer_norm else None),
                                  ('activation', self.activation_fn() if self.activation_fn else None),
                                  ('dropout', nn.Dropout(p=self.dropout_rate) if (self.dropout_rate and self.dropout_rate > 0) else None)])

#         self._initialize_weights(all_layers['linear'])  # Initialize weights based on activation function
        return nn.Sequential(OrderedDict((k, v) for k, v in all_layers.items() if v is not None))
    
    def _initialize_weights(self, layer):
        """Initialize weights based on the activation function."""
        if isinstance(self.activation_fn, type):
            if self.activation_fn == nn.LeakyReLU:
                nn.init.kaiming_uniform_(layer.weight, nonlinearity='leaky_relu')
            elif self.activation_fn == nn.ReLU or issubclass(self.activation_fn, nn.ReLU):
                nn.init.kaiming_uniform_(layer.weight, nonlinearity='relu')
            elif self.activation_fn == nn.Tanh or issubclass(self.activation_fn, nn.Tanh):
                nn.init.xavier_uniform_(layer.weight)
            elif self.activation_fn == nn.Sigmoid or issubclass(self.activation_fn, nn.Sigmoid):
                nn.init.xavier_uniform_(layer.weight)
            else:
                nn.init.kaiming_uniform_(layer.weight)  # Default to He initialization
        else:
            nn.init.kaiming_uniform_(layer.weight)  # Default initialization

        if layer.bias is not None:
            nn.init.zeros_(layer.bias)

    def forward(self, x):
        return self.fc_layers(x)   

class GaussianVariationalEncoder(nn.Module):
    """
    Generative (Gaussian) projection from input TF activity to a latent space (encoder) or vice-versa (decoder).
    Adapted from scVI's `Encoder`.
    """

    DEFAULT_HYPER_PARAMS = {f"vae_{key}": value for key, value in 
                            {**FCLayers.DEFAULT_HYPER_PARAMS, 
                            **{'n_hidden_nodes': [1024, 768, 512], 'var_min': 1e-4}}.items()}
    del DEFAULT_HYPER_PARAMS['vae_spectral_norm']
    
    def __init__(self, n_features: int, n_latent: int,
                 var_min: float = 1e-4,
                 decode: bool = False,
                 n_hidden_nodes: List[int] = [1024, 768, 512],
                 batch_momentum: float = 0.01,
                 layer_norm: bool = False,
                 dropout_rate: int | float = 0.1,
                 activation_fn: nn.Module | None = nn.LeakyReLU,
                #  initialize: bool = False, 
                 dtype: torch.dtype=torch.float32,
                 device: str = 'cpu', 
                 seed: int = 888
                ):
        """Initialize variational decoder.

        Parameters
        ----------
        n_features : int
            the full number of features input to the encoder
        n_latent : int, optional
            dimension (no. of features) of the latent space
        var_min : float, optional
            Minimum value for the variance, by default 1e-4. Used for numerical stability
        decode : bool, optional
            whether to encode into latent space (False) or decode into full feature space (True)
        n_hidden_nodes : List[int], optional
            number of hidden nodes per hidden layer, by default [1024, 768, 512]
            each element in the list corresponds to one hidden layer (i.e., no. of hidden layers = length of list)
        batch_momentum : float, optional
            `momentum` parameter for `BatchNorm` layer, by default .01
            If None, a `BatchNorm` is not added
        layer_norm : bool, optional
            whether to have `LayerNorm` layers or not, by default False
        dropout_rate : int | float, optional
            dropout rate to apply to each of the hidden layers, by default 0.1
            If None, dropout is not added
        activation_fn : nn.Module | None, optional
            non-linear Pytorch activation function, by default nn.ReLU. No activation if set to None
        initialize: bool, optional
            whether to initialize the linear layer weights using `torch.nn.init`, by default False
        dtype : torch.dtype, optional
            datatype to store values in torch, by default torch.float32
        device : str, optional
            whether to use gpu ("cuda") or cpu ("cpu"), by default "cpu"
        seed : int
            random seed for torch and numpy operations, by default 888
        """
        super().__init__()

        self.dtype = dtype
        self.device = device
        self.seed = seed
        
        # self.z_transformation = _identity # z has gaussian distribution
        # self.var_activation = torch.exp # ensure positivity of variance
        self.var_min = var_min
    
        if n_hidden_nodes != sorted(n_hidden_nodes)[::-1]:
            warnings.warn('You have specified an encoder/decoder layer that does not have a consistent change in # of nodes per hidden layer')
        
        if decode:
            layers_dim = [n_latent] + n_hidden_nodes[::-1]
            n_encode_in, n_encode_out = n_hidden_nodes[0], n_features
        else:
            layers_dim = [n_features] + n_hidden_nodes
            n_encode_in, n_encode_out = n_hidden_nodes[-1], n_latent
        
        if self.seed:
            set_seeds(self.seed)
        self.hidden_layers = FCLayers(layers = layers_dim,
                                      batch_momentum = batch_momentum,
                                      layer_norm = layer_norm,
                                      spectral_norm = False,
                                      dropout_rate = dropout_rate,
                                    #   initialize = initialize,
                                      activation_fn = activation_fn,
                                      dtype = self.dtype, device = self.device)
        self.z_mean = nn.Linear(n_encode_in, n_encode_out, device = self.device, dtype = self.dtype)
        self.z_log_var = nn.Linear(n_encode_in, n_encode_out, device = self.device, dtype = self.dtype) # log of the variance
    
    def forward(self, x):
        """Calculates the latent space distribution and samples from it.
    
        Returns
        -------
        z_mu : torch.Tensor
            the mean (mu) parameter for each feature in latent space
        z_log_sigma_squared : torch.Tensor
            the log-variance parameter for each feature in latent space
        z : torch.Tensor
            the sample drawn from N(z_m, z_v)
        """
        h = self.hidden_layers(x)
        z_mu = self.z_mean(h)
        z_log_sigma_squared = self.z_log_var(h) # log-variance
        z_sigma = torch.exp(z_log_sigma_squared/2.) + self.var_min # std from log-var trick 

        # # scVI sampling
        # dist = torch.distributions.Normal(z_m, z_v.sqrt())
        # z = self.z_transformation(dist.rsample())
        
        # reparameterization 
        set_seeds(self.seed)
        epsilon = torch.randn_like(z_mu, dtype = self.dtype, device = self.device)
        z = z_mu + z_sigma*epsilon # re-parameterization trick

        return z_mu, z_log_sigma_squared, z
    
    @staticmethod
    def KL_divergence_standard(z_mu, z_log_sigma_squared, scaling_factor):
        """Calculates KL divergence between the VAE estimated parameters and the standard normal distribution. 

        Parameters
        ----------
        z_mu : torch.Tensor
            the mean (mu) parameter for each feature in latent space
        z_log_sigma_squared : torch.Tensor
            the log-variance parameter for each feature in latent space
        scaling_factor : float
            scales the KL divergence by a constant, to make it more in line with other loss terms
            
        Returns
        -------
        kl_div : torch.Tensor
            the average KL divergence across samples. First, calculated for each sample, then averaged across samples.
        """
        kl_div = -0.5 * torch.sum(1 + z_log_sigma_squared - z_mu**2 - torch.exp(z_log_sigma_squared), axis = 1) # sample-wise kl divergance 
        return scaling_factor*kl_div.mean() # average across samples
    

    def KL_divergence(self, z_mu, z_log_sigma_squared, scaling_factor, prior_mu, prior_sigma):
        """Calculates KL divergence between the VAE estimated parameters and a normal distribution with mean prior_mu and std prior_sigma. 

        Parameters
        ----------
        z_mu : torch.Tensor
            the mean (mu) parameter for each feature in latent space
        z_log_sigma_squared : torch.Tensor
            the log-variance parameter for each feature in latent space
        scaling_factor : float
            scales the KL divergence by a constant, to make it more in line with other loss terms
        prior_mu : torch.tensor
            the desired mean of the distribution
        prior_sigma : torch.tensor
            the desired std of the distribution
            
        Returns
        -------
        kl_div : torch.Tensor
            the average KL divergence across samples. First, calculated for each sample, then averaged across samples.
        """
        # if not torch.is_tensor(prior_mu):
        #     prior_mu = torch.tensor(prior_mu, device=self.device, dtype=self.dtype)
        # if not torch.is_tensor(prior_sigma):
        #     prior_sigma = torch.tensor(prior_sigma, device=self.device, dtype=self.dtype)

        if prior_mu == 0 and prior_sigma == 1:
            return self.KL_divergence_standard(z_mu, z_log_sigma_squared, scaling_factor)
        prior_mu = prior_mu.expand_as(z_mu)
        prior_var = prior_sigma.pow(2).expand_as(z_mu)

        var = torch.exp(z_log_sigma_squared)
        kl_div = 0.5 * torch.sum(
            torch.log(prior_var) - z_log_sigma_squared +
            (var + (z_mu - prior_mu).pow(2)) / prior_var - 1,
            dim=1
        )
        return scaling_factor*kl_div.mean() # average across samples

    
    def L2_reg(self, lambda_L2: Annotated[float, Ge(0)] = 0):
        """Get the L2 regularization term for the linear layers' parameters.
        
        Parameters
        ----------
        lambda_2 : Annotated[float, Ge(0)]
            the regularization parameter, by default 0 (no penalty) 
        
        Returns
        -------
        l2_loss : torch.Tensor
            the regularization term
        """
        regularization_loss = 0
        if lambda_L2 != 0:
            for layer in self.modules():
                if isinstance(layer, nn.Linear):
                    regularization_loss += torch.sum(torch.square(layer.weight))
                    if layer.bias is not None:
                        regularization_loss += torch.sum(torch.square(layer.bias))
            regularization_loss = lambda_L2 * regularization_loss
        
        return regularization_loss
    
    
class CatDiscriminator(nn.Module):
    """"Discriminator for categorical covariates in adversarial training of scLEMBAS.
    Adapted from scVI's `Classifier`.
    """
    
    DEFAULT_HYPER_PARAMS = {**FCLayers.DEFAULT_HYPER_PARAMS, 
                            **{'n_hidden_nodes': [16, 16, 16]}, 
                           'bionet_activation': False, 
                           'smooth_labels': False, 
                           'epsilon_smooth': 0.1}
    
    def __init__(
        self,
        n_features_in: int,
        n_labels: int,
        n_hidden_nodes: List[int] = [16, 16, 16],
        batch_momentum: float = 0.01,
        layer_norm: bool = False,
        spectral_norm: bool = False,
        dropout_rate: int | float = 0.1,
        activation_fn: nn.Module | None = nn.LeakyReLU,
        bionet_activation: bool = False, 
        rnn_params: dict = {'activation_function': 'MML', 'leak': 0.01}, 
        smooth_labels: bool = False, 
        epsilon_smooth: float = 0.1,
        # initialize: bool = True,
        dtype: torch.dtype=torch.float32,
        device: str = 'cpu', 
        seed: int = 888, 
    ):
        """Initialize discriminator

        Parameters
        ----------
        n_features_in : int
            number of inpute features to discriminator (should be number of latent features for scLEMBAS)
        n_labels : int
            number of categories for the given categorical covariate
        n_hidden_nodes : List[int], optional
            number of hidden nodes per hidden layer, by default [64]
            each element in the list corresponds to one hidden layer (i.e., no. of hidden layers = length of list), by default [16, 16, 16]
        batch_momentum : float, optional
            `momentum` parameter for `BatchNorm` layer, by default .01
            If None, a `BatchNorm` is not added
        layer_norm : bool, optional
            whether to have `LayerNorm` layers or not, by default False
        spectral_norm : bool, optional
            whether to apply spectral normalization (`torch.nn.utils.spectral_norm`) to the linear layers of the model
        dropout_rate : int | float, optional
            dropout rate to apply to each of the hidden layers, by default 0.1
            If None, dropout is not added
        activation_fn : nn.Module | None, optional
            non-linear Pytorch activation function, by default nn.ReLU. No activation if set to None
        bionet_activation: bool, optional
            whether to classify the direct generator output (False) or 
            the output once it's been run through the RNN (True) (i.e., run through the bionet activation function).
            The motivation here is from obervations that any lingering information (particularly non-linear) in the global bias 
            will be amplified by the non-linear function of the RNN
        rnn_params: dict, optional
          bionetwork 'activation_function' and 'leak'; see `model.bionetwork.forward` for details; necessary to know the exact
          bionet activation function being used
          only required if bionet_activation is True
        smooth_labels: bool, optional
            whether to smooth the labels (with epsilon parameter) (True) or not (False), by default False
        epsilon_smooth: float, optional
            if smoothing labels, epsilon parameter to apply smoothing with
        initialize: bool, optional
            whether to initialize the linear layer weights using `torch.nn.init`, by default True
        dtype : torch.dtype, optional
            datatype to store values in torch, by default torch.float32
        device : str
            whether to use gpu ("cuda") or cpu ("cpu"), by default "cpu"
        seed : int
            random seed for torch and numpy operations, by default 888
        """
        super().__init__()
        self.n_labels = n_labels
        self.device = device
        self.dtype = dtype
        self.seed = seed
        self.bionet_activation = bionet_activation
        self.smooth_labels = smooth_labels
        assert 0 < epsilon_smooth < 1, "epsilon_smooth must be between (0,1)"
        self.epsilon_smooth = epsilon_smooth
        

        if self.n_labels > 2: # multi-class
            if self.smooth_labels:
                self.loss_fn = self.smooth_multi_loss
            else:
                self.loss_fn = nn.CrossEntropyLoss() # applies softmax to logits prior to CE
            out_features = self.n_labels
        elif self.n_labels == 2: # binary
            if self.smooth_labels:
                self.loss_fn = self.smooth_binary_loss
            else:
                self.loss_fn = nn.BCEWithLogitsLoss() # applies sigmoid to logits prior to CE
            out_features = 1
        else:
            raise ValueError('There are no distinct classes.')


        
        cat_layers = []
        if self.bionet_activation: 
            cat_layers.append(activation_function_torch_map[rnn_params['activation_function']](leak = rnn_params['leak']))
        if self.seed:
            set_seeds(self.seed)
        cat_layers.append(FCLayers(layers = [n_features_in] + n_hidden_nodes, 
                                   batch_momentum = batch_momentum, # since bias is just a vector 
                                   layer_norm = layer_norm, 
                                   spectral_norm = spectral_norm,
                                   dropout_rate = dropout_rate, 
                                   activation_fn = activation_fn, 
                                #    initialize = initialize,
                                   dtype = self.dtype, device = self.device))
        cat_layers.append(FCLayers(layers = [n_hidden_nodes[-1], out_features], 
                                   dtype = self.dtype, device = self.device,
                                   batch_momentum = None, layer_norm = False, 
                                   spectral_norm = spectral_norm, dropout_rate = None, activation_fn = None))
                                #   initialize = initialize))

        self.classifier = nn.Sequential(*cat_layers)

    def forward(self, x):
        """Returns logits for labels"""
        return self.classifier(x) 
    
    def smooth_binary_loss(self, logits, labels):
        smoothed_labels = labels * (1 - self.epsilon_smooth) + self.epsilon_smooth
        return F.binary_cross_entropy_with_logits(logits, smoothed_labels, reduction='mean')
    
    def smooth_multi_loss(self, logits, labels):
        one_hot = F.one_hot(labels, num_classes=self.n_labels)
        smoothed_labels = one_hot * (1 - self.epsilon_smooth) + self.epsilon_smooth / self.n_labels
        log_probs = F.log_softmax(logits, dim=1)
        return F.kl_div(log_probs, smoothed_labels, reduction='batchmean')
    
    def L2_reg(self, lambda_L2: Annotated[float, Ge(0)] = 0):
        """Get the L2 regularization term for the linear layers' parameters.
        
        Parameters
        ----------
        lambda_2 : Annotated[float, Ge(0)]
            the regularization parameter, by default 0 (no penalty) 
        
        Returns
        -------
        regularization_loss : torch.Tensor
            the regularization term
        """
        regularization_loss = torch.tensor(0.0, device=self.device, dtype=self.dtype)
        if lambda_L2 != 0:
            for layer in self.classifier.modules():
                if isinstance(layer, nn.Linear):
                    regularization_loss += torch.sum(torch.square(layer.weight))
                    if layer.bias is not None:
                        regularization_loss += torch.sum(torch.square(layer.bias))
            regularization_loss = lambda_L2 * regularization_loss
        
        return regularization_loss

    def get_probability(self, y):
        """Calculate the probability from output logits."""
        if self.n_labels > 2:
            return F.softmax(y.detach(), dim=-1)
        else:
            return F.sigmoid(y.detach(), dim = -1) # probability of the "positive" (labeled "1") layer
        
    def random_loss(self, class_probs):
        """
        Calculates the expected loss of a discriminator with random predictions.

        To estimate the baseline KL divergence for a random discriminator under label smoothing, 
        we compute the average KL divergence between each smoothed one-hot label 
        (i.e., the softened target for each class) and a fixed "random" prediction distribution (class-weighted). 
        This simulates the expected loss a discriminator would incur if it always output the same uninformative 
        prediction, allowing us to benchmark how well it is performing compared to chance. 
        By averaging across all possible true classes, we account for the full range of label configurations 
        the discriminator might encounter.


        Parameters
        ----------
        class_probs 
            an array of the probabilities of each class for weighting unbalanced classes in random loss calculation
        """

    #     class_probs = tf_adata[train_cells,:].obs[cat_col].value_counts(normalize = True).values
        if self.n_labels != 2 and self.smooth_labels:
            loss_type = 'KL_divergence'
        else:
            loss_type = 'cross_entropy'

        if len(class_probs) != self.n_labels:
            raise ValueError('The class_probs must be the same length as self.n_labels')

        if loss_type == 'cross_entropy':
            return -np.sum(class_probs * np.log(class_probs))
        else: # loss_type == 'KL_divergence':
            total_kl = 0

            Q = torch.tensor(class_probs, dtype=torch.float32) # random prediction
            log_Q = torch.log(Q + 1e-10)

            for i in range(self.n_labels):
                # Smoothed target for class i
                one_hot = np.zeros(self.n_labels)
                one_hot[i] = 1
                smoothed = one_hot * (1 - self.epsilon_smooth) + self.epsilon_smooth / self.n_labels

                P = torch.tensor(smoothed, dtype=torch.float32) # label-smoothing adjusted true target

                kl = F.kl_div(log_Q, P, reduction='sum')
                total_kl += class_probs[i] * kl.item() # gives a weighted average

            return total_kl
        
