"""
Read and write python objects.
"""

import pathlib
import pickle
from typing import Any
import os

import scanpy as sc
import anndata


def read_pickled_object(file_name: str):
    """Read an object as a pickled file.

    Parameters
    ----------
    file_name : str
        'full/path/to/file.pickle'
    
    Returns
    -------
    pickled_object
        the pickled object
    """
    with open(file_name, 'rb') as handle:
        pickled_object = pickle.load(handle)
    return pickled_object

def write_pickled_object(object: Any, file_name: str) -> None:
    """Save an object as a pickled file.

    Parameters
    ----------
    object : Any
        object to save
    file_name : str
        'full/path/to/file.pickle'
    """
    if '.' in file_name:
        p = pathlib.Path(file_name)
        extensions = "".join(p.suffixes)
        file_name = str(p).replace(extensions, '.pickle')
    else:
        file_name = file_name + '.pickle'

    with open(file_name, 'wb') as handle:
        pickle.dump(object, handle)

def write_tfad(tf_adata: anndata.AnnData, file_name: str):
    """Write the tf adata object generated by embed_tf_activity with the PCA model

    Parameters
    ----------
    tf_adata : anndata.AnnData
        object to write
    file_name : str
        full path and file name to write tf_adata
    """
    if 'pca_mod' in tf_adata.uns['pca']:
        write_pickled_object(tf_adata.uns['pca']['pca_mod'], file_name.replace('.h5ad', '.pickle'))
    del tf_adata.uns['pca']['pca_mod']
    tf_adata.write_h5ad(os.path.join(file_name))

def read_tfad(file_name: str):
    """Read the tf adata object generated by embed_tf_activity with the PCA model

    Parameters
    ----------
    file_name : str
        full path and file name to read tf_adata
    """

    tf_adata = sc.read_h5ad(file_name)
    file_name = file_name.replace('.h5ad', '.pickle')
    if os.path.isfile(file_name):
        tf_adata.uns['pca']['pca_mod'] = read_pickled_object(file_name)

    return tf_adata