"""
Read and write python objects.
"""

import pathlib
import pickle
from typing import Any
import os

import scanpy as sc
import anndata


def read_pickled_object(file_name: str):
    """Read an object as a pickled file.

    Parameters
    ----------
    file_name : str
        'full/path/to/file.pickle'
    
    Returns
    -------
    pickled_object
        the pickled object
    """
    with open(file_name, 'rb') as handle:
        pickled_object = pickle.load(handle)
    return pickled_object

def write_pickled_object(object: Any, file_name: str) -> None:
    """Save an object as a pickled file.

    Parameters
    ----------
    object : Any
        object to save
    file_name : str
        'full/path/to/file.pickle'
    """
    if '.' in file_name:
        p = pathlib.Path(file_name)
        extensions = "".join(p.suffixes)
        file_name = str(p).replace(extensions, '.pickle')
    else:
        file_name = file_name + '.pickle'

    with open(file_name, 'wb') as handle:
        pickle.dump(object, handle)

def write_tfad(tf_adata: anndata.AnnData, file_name: str):
    """Write the tf adata object generated by embed_tf_activity with the PCA model

    Parameters
    ----------
    tf_adata : anndata.AnnData
        object to write
    file_name : str
        full path and file name to write tf_adata
    """
    for embedding in ['pca', 'umap', 'pls', 'umap_pls']:
        if embedding in tf_adata.uns:
            if embedding + '_mod' in tf_adata.uns[embedding]:
                write_pickled_object(tf_adata.uns[embedding][embedding + '_mod'], 
                             file_name.replace('.h5ad', embedding + '.pickle'))
                del tf_adata.uns[embedding][embedding + '_mod']

                if embedding == 'pls':
                    for encoder in ['encoder_x', 'encoder_y']:
                        write_pickled_object(tf_adata.uns[embedding][encoder], 
                                 file_name.replace('.h5ad', encoder + '.pickle'))
                        del tf_adata.uns[embedding][encoder]
    
    tf_adata.write_h5ad(os.path.join(file_name))

def read_tfad(file_name: str):
    """Read the tf adata object generated by embed_tf_activity with the PCA model

    Parameters
    ----------
    file_name : str
        full path and file name to read tf_adata
    """

    tf_adata = sc.read_h5ad(file_name)
    for embedding in ['pca', 'umap', 'pls', 'umap_pls']:
        file_name_ = file_name.replace('.h5ad', embedding +'.pickle')
        if os.path.isfile(file_name_):
            tf_adata.uns[embedding][embedding + '_mod'] = read_pickled_object(file_name_)

            if embedding == 'pls':
                for encoder in ['encoder_x', 'encoder_y']:
                    tf_adata.uns[embedding][encoder] = read_pickled_object(file_name.replace('.h5ad', encoder + '.pickle'))

    return tf_adata